const date = new Date();
const day = date.getDay();
const month = date.getMonth() + 1;
const year = date.getFullYear();
const villas = [
  {
    name: "Avanti",
    location: {
      country: "USA",
      region: "Saint Martin",
      city: "Terres Basses",
    },
    startingPrice: "4215",
    images: [
      "product1/1.jpg",
      "product1/2.jpg",
      "product1/3.jpg",
      "product1/4.jpg",
      "product1/5.jpg",
      "product1/6.jpg",
      "product1/7.jpg",
      "product1/8.jpg",
      "product1/9.jpg",
      "product1/10.jpg",
      "product1/11.jpg",
      "product1/12.jpg",
      "product1/13.jpg",
      "product1/14.jpg",
      "product1/15.jpg",
      "product1/16.jpg",
      "product1/17.jpg",
      "product1/18.jpg",
      "product1/19.jpg",
      "product1/20.jpg",
    ],
    availableDates: {
      startDate: "", //`${day}-${month}-${year}`,
      endDate: "",
    },
    Description:
      "This five-bedroom home is ideally located to offer breathtaking views throughout as its elevated position allows you to gaze across the glistening waters of Grand tang toward Baie Longue and the Caribbean Sea beyond, with the island of Saba visible on the distant horizon. Inside you will find a modern, open-plan living and dining area, a media room with a large flat-screen TV, and a chic, fully-equipped kitchen with a service hatch that allows meals to be easily passed through to be enjoyed on the covered terrace. Each bedroom contains a king-size bed and features an en-suite bathroom with dual vanities, a walk-in shower and an outdoor shower. The master suite has access to a private terrace with a daybed, table & chairs, and a hot tub, while the other bedrooms have access to exterior areas of the home such as the pool terrace. Outside you will find an expansive covered terrace with comfortable outdoor lounge seating, an alfresco dining area, and a breakfast bar located beside the kitchenï¿½s service hatch. A lighted gazebo with further outdoor lounge seating and a wet bar stands beside the property's unique L-shaped pool and provides direct step access. Alternatively, the pool has been designed to offer a beach-style slope access, and the island daybed provides a fantastic spot to relax atop the water while the rest of the family take a dip.",
    Facilities: {
      capacity: 10,
      BuildArea: "104544 sq.ft",
      bedRoom: 5,
      bathRoom: 12,
      beds: 10,
      games: 3, //for first page
    },
    Equipments: {
      outside: [
        "Sunloungers",
        "Breakfast bar",
        "Covered terrace",
        "Gazebo with wet bar",
        "Alfresco dining area",
        "BBQ",
        "Outdoor lounge area",
        "Poolside lounge area",
        "Landscaped gardens",
      ],
      inside: [
        "Private pool",
        "Sunloungers",
        "Alfresco dining area",
        "BBQ",
        "Outdoor lounge area",
        "Poolside lounge area",
        "Landscaped gardens",
      ],
    },
  },
  {
    name: "Kempa",
    location: {
      country: "USA",
      region: "California",
      city: "Palm Springs",
    },
    startingPrice: "3700",
    images: [
      "product2/1.jpg",
      "product2/2.jpg",
      "product2/3.jpg",
      "product2/4.jpg",
      "product2/5.jpg",
      "product2/6.jpg",
      "product2/7.jpg",
      "product2/8.jpg",
      "product2/9.jpg",
      "product2/10.jpg",
      "product2/11.jpg",
      "product2/12.jpg",
      "product2/13.jpg",
      "product2/14.jpg",
      "product2/15.jpg",
      "product2/16.jpg",
      "product2/17.jpg",
      "product2/18.jpg",
      "product2/19.jpg",
      "product2/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "Located in the heart of Palm Desert, this exquisite mansion is an oasis of luxury in the midst of some of the most breathtaking landscapes in California. Secluded, relaxing, and boasting 9000 square feet of beautifully designed indoor and outdoor living space, it is perfect for group getaways or special vacations with the whole family. With 3 buildings, including 8-bedrooms, 10-bathrooms and a capacity to sleep upwards of 18 guests, Kempa Villa has got all the space that you could wish for. This resort-style villa is designed with making memories in mind. From the grand open-plan living and dining room for family meals and swapping stories of the day's adventures, to blissfully comfortable bedrooms, and a large kitchen and breakfast bar, the villa offers guests wall-to-wall luxury living. While the inside of the home certainly has the 'wow factor', the amazing amenities don't stop at the front door. Kempa Villaâ€™s outdoor spaces are also breathtaking, with a luxurious private heated infinity pool, shuffleboard, a zen-inducing peace pond, a cozy firepit, and sweeping views of nearby mountains. Aside from the main villa, the villa also has an on-site bungalow, just as luxurious. The bungalow provides 3 bedrooms, gourmet kitchen, living area, covered terraces and its very own private garden. The villa is gated and private, and even has helicopter access, landscaped gardens, and its own fruit orchard. In short, this magnificent villa is an irresistible place to spend an unforgettable Palm Desert vacation.",
    Facilities: {
      capacity: 20,
      BuildArea: "9000sq ft",
      bedRoom: 8,
      bathRoom: 10,
      beds: 10,
      games: 3, //for first page
    },
    Equipments: {
      outside: [
        "Private infinity pool",
        "Hot tub (pool heat required, complimentary upon request)",
        "Sunloungers",
        "Barbecue",
        "Alfresco dining area",
        "Outdoor lounge seating",
        "Firepit (complimentary upon request)",
        "Large private pond with beach area",
        "Vineyard with Chardonnay grapes",
        "Orchard with mature fruit trees",
      ],
      inside: [
        "Flat-screen TV",
        "Home gym with all equipments",
        "Shuffleboard and pool table",
        "Oversized chess",
        "Air conditioning throughout",
        "Complimentary wifi",
        "Washer and dryer",
        "Iron and ironing board",
      ],
    },
  },
  {
    name: "Reunion",
    location: {
      country: "USA",
      region: "Florida",
      city: "Orlando",
    },
    startingPrice: "2716",
    images: [
      "product3/1.jpg",
      "product3/2.jpg",
      "product3/3.jpg",
      "product3/4.jpg",
      "product3/5.jpg",
      "product3/6.jpg",
      "product3/7.jpg",
      "product3/8.jpg",
      "product3/9.jpg",
      "product3/10.jpg",
      "product3/11.jpg",
      "product3/12.jpg",
      "product3/13.jpg",
      "product3/14.jpg",
      "product3/15.jpg",
      "product3/16.jpg",
      "product3/17.jpg",
      "product3/18.jpg",
      "product3/19.jpg",
      "product3/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "No expense has been spared in creating this incredible villa located in Reunion Resort. The perfect choice for get-togethers and memory-making, it boasts 9 en-suite bedrooms, 12.5 bathrooms and enough space for up to 22 guests. Just inside the front door, the foyer features a sweeping double staircase and tall windows that allow natural light to flood in. Polished floors lead to a variety of living spaces including a large dining room, a stylish lounge and a fully equipped kitchen with a breakfast bar. For entertainment, thereï¿½s an amazing movie theater and a state-of-the-art game room with a bowling alley, air hockey, arcade games and a pool table. The gym and indoor sports courts are the perfect place to work up a sweat, while the in-villa spa is a place to relax with its sauna, steam room and hot tub. Outside, thereï¿½s a large terrace with a private pool, spillover tub and luxury poolside loungers. The terrace has a choice of lounge areas as well as a covered lanai with an outdoor kitchen and alfresco dining area.",
    Facilities: {
      capacity: 22,
      BuildArea: "15500 sq.ft",
      bedRoom: 9,
      bathRoom: 12,
      beds: 15,
      games: 6, //for first page
    },
    Equipments: {
      outside: [
        "Sunloungers",
        "Breakfast bar",
        "Covered terrace",
        "BBQ",
        "Outdoor lounge area",
        "Poolside lounge area",
        "Landscaped gardens",
      ],
      inside: [
        "Open-plan living area",
        "flat-screen TV and comfortable sofas",
        "Fully equipped kitchen",
        "Breakfast bar with seating",
        "Dining table and chairs",
        "games consoles",
        "Home theater with projector screen",
        "Indoor basketball",
        "racquetball court",
      ],
    },
  },
  {
    name: "Ski",
    location: {
      country: "USA",
      region: "New Mexico",
      city: "Taos Ski Valley",
    },
    startingPrice: "670",
    images: [
      "product4/1.jpg",
      "product4/2.jpg",
      "product4/3.jpg",
      "product4/4.jpg",
      "product4/5.jpg",
      "product4/6.jpg",
      "product4/7.jpg",
      "product4/8.jpg",
      "product4/9.jpg",
      "product4/10.jpg",
      "product4/11.jpg",
      "product4/12.jpg",
      "product4/13.jpg",
      // "product4/14.jpg",
      // "product4/15.jpg",
      // "product4/16.jpg",
      // "product4/17.jpg",
      // "product4/18.jpg",
      // "product4/19.jpg",
      // "product4/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "Located in the mountaintop Kachina Village, this home invites guests to experience the crisp air and stunning beauty of Taos Ski Valley.Constructed with locally sourced materials, including dead-standing timbers, this charming European-style home features hardwood floors and beams, galvanized steel panels and baseboards throughout, and a minimalist style, harkening to the mining history of Kachina Village.In the living room, a mid-century sectional sofa faces a chic, steel firebox and large-screen TV, accented by an industrial coffee table. Through a grand entryway, the living area flows into an eat-in kitchen, where a family-style dining table seats up to 8 guests. Fully equipped with stainless steel appliances and a wet bar, the kitchen offers plenty of room for crafting hot cocoa and cocktails after a day on the slopes, or baking a batch of cookies on a snowed-in afternoon.",
    Facilities: {
      capacity: 8,
      BuildArea: "2200sq ft",
      bedRoom: 4,
      bathRoom: 3,
      beds: 4,
      games: 1, //for first page
    },
    Equipments: {
      outside: [
        "Outdoor lounge seating",
        "Vineyard with Chardonnay grapes",
        "Orchard with mature fruit trees",
      ],
      inside: [
        "WiFI",
        "Centralised Heater",
        "BBQ",
        "Washer and dryer",
        "Iron and ironing board",
      ],
    },
  },
  {
    name: "Reef",
    location: {
      country: "Caribbean",
      region: "Jamaica",
      city: "Ocho Rios",
    },
    startingPrice: "6720",
    images: [
      "product5/1.jpg",
      "product5/2.jpg",
      "product5/3.jpg",
      "product5/4.jpg",
      "product5/5.jpg",
      "product5/6.jpg",
      "product5/7.jpg",
      "product5/8.jpg",
      "product5/9.jpg",
      "product5/10.jpg",
      "product5/11.jpg",
      "product5/12.jpg",
      "product5/13.jpg",
      "product5/14.jpg",
      "product5/15.jpg",
      "product5/16.jpg",
      "product5/17.jpg",
      "product5/18.jpg",
      "product5/19.jpg",
      "product5/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "This truly breathtaking 9-bedroom 9.5-bathroom contemporary villa is located right on the waters edge in beautiful Ocho Rios and has enough space to sleep up to 18 guests in style. Downstairs features a spacious open-plan living and dining area, a fully-equipped kitchen, a media room and game room and 2 en-suite bedrooms, each with access to an ocean facing veranda. Upstairs, you will find 4 further en-suite bedrooms, each with a private balcony. The remaining bedrooms are located in the cottage with 2 en-suite bedrooms on the ground level and a further en-suite bedroom on the top level, there's also a separate living area and a service kitchen. Outside, you will find a private infinity pool, a 14-person hot tub, a poolside covered verandah with a seating area and a bar and plenty of sunloungers and casual seating areas throughout the majestic gardens. With an abundance of sporting facilities, this extensive home is perfect for an active family; guests can enjoy access to a private tennis court, a pickleball court, as well as complimentary paddle boards, kayaks and scuba equipment to swim out to the tropical reefs.",
    Facilities: {
      capacity: 18,
      BuildArea: "2200sq ft",
      bedRoom: 9,
      bathRoom: 10,
      beds: 9,
      games: 1, //for first page
    },
    Equipments: {
      outside: [
        "Private infinity pool",
        "Submerged sun shelf with loungers",
        "Additional plunge pool (next to cottage)",
        "14-person hot tub",
        "Sunloungers",
        "Landscaped gardens",
        "Mutiple casual seating areas",
        "Almond Tree grill terrace",
      ],
      inside: [
        "Air-conditioned conference room",
        "Sonos sound system throughout",
        "Smart TVs in living and bedrooms",
        "Media room with flat-screen TV",
        "Game room with pool table",
        "Paddle boards, kayaks and snorkeling",
        "Private floodlit tennis court",
        "Private pickleball court",
      ],
    },
  },
  {
    name: "P-Point",
    location: {
      country: "Caribbean",
      region: "Antigua",
      city: "Palm-Point",
    },
    startingPrice: "8500",
    images: [
      "product6/1.jpg",
      "product6/2.jpg",
      "product6/3.jpg",
      "product6/4.jpg",
      "product6/5.jpg",
      "product6/6.jpg",
      "product6/7.jpg",
      "product6/8.jpg",
      "product6/9.jpg",
      "product6/10.jpg",
      "product6/11.jpg",
      "product6/12.jpg",
      "product6/13.jpg",
      "product6/14.jpg",
      "product6/15.jpg",
      "product6/16.jpg",
      "product6/17.jpg",
      "product6/18.jpg",
      "product6/19.jpg",
      "product6/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "This 8-bedroom villa is fantastically located in Antigua's Jolly Harbour. Spread across the main house and boat house, guests of this home have access to their own private beach included with the rental of this property. Inside the main house you will find six immaculately furnished, spacious en-suite bedrooms. Luxury living will become the norm during your stay here as the stylish and modern open-plan living area offers a vast amount of space to enjoy your downtime, and the fully equipped kitchen offers all the equipment required to cook up any of your favorite meals, or have a chef cook them for you during rentals taking place over the summer season. The villa also comes with an expansive pool terrace which features a private swimming pool and hot tub set beside a covered area with an alfresco dining area, and a gazebo with deluxe sunloungers.",
    Facilities: {
      capacity: 18,
      BuildArea: "3200sq ft",
      bedRoom: 6,
      bathRoom: 8,
      beds: 8,
      games: 1, //for first page
    },
    Equipments: {
      outside: [
        "Private pool",
        "Private hot tub",
        "Private beach",
        "Sunloungers",
        "Covered terrace",
        "Gazebo",
        "Alfresco dining area",
        "Outdoor lounge area",
        "additional alfresco dining area",
        "Landscaped gardens",
        "Yacht dock",
      ],
      inside: [
        "Air-conditioned",
        "Smart TVs in living and bedrooms",
        "Game room with pool table",
        "Wifi",
        "BBQ",
        "Washer and dryer",
        "Iron and ironing board",
      ],
    },
  },
  {
    name: "Ixfalia",
    location: {
      country: "Caribbean",
      region: "St Barthelemy",
      city: "St Jean",
    },
    startingPrice: "8000",
    images: [
      "product7/1.jpg",
      "product7/2.jpg",
      "product7/3.jpg",
      "product7/4.jpg",
      "product7/5.jpg",
      "product7/6.jpg",
      "product7/7.jpg",
      "product7/8.jpg",
      "product7/9.jpg",
      "product7/10.jpg",
      "product7/11.jpg",
      "product7/12.jpg",
      "product7/13.jpg",
      "product7/14.jpg",
      "product7/15.jpg",
      "product7/16.jpg",
      "product7/17.jpg",
      "product7/18.jpg",
      "product7/19.jpg",
      "product7/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "The newly built Villa Ixfalia takes much of its design inspiration from an unlikely source: the vibrant, soulful continent of Africa. You can see that in the ethereal bird's-nest lamps that hang from the ceilings and the massive shell necklaces on display in a bedroom. It is transporting in the most literal of ways as the owners set out to evoke a sense of voyage to far-off places and discovery of exotic treasures and filled the house with items brought back from their sojourns. The feeling of worldly travel that pervades this luxury rental home marries easily with the natural beauty of St. Barth, and materials such as wood and straw feature prominently in the furniture and finishings.Thanks to its hillside location in the Morne des Diamands above St. Jean, Villa Ixfalia has spectacular views over the Eden Rock hotel and St. Jean Bay, as well as a high level of privacy. The heated swimming pool has an unusual shape that takes the best advantage of those sea views. The garden is filled with exotic plants and trees, and dramatic rock formations rise strikingly in the back. Along with design choices made to maximize those views, the villa also benefits from a layout that makes the most of the cool sea breezes coming off the bay.It is not just the circulating fresh air that makes Villa Ixfalia feel like a comfortable home. There is a Zen vibe about the way it has been designed and laid out. There are plenty of indoor, sunny and shaded outdoor places to relax and enjoy the company of your loved ones, be they family or a group of friends.",
    Facilities: {
      capacity: 8,
      BuildArea: "1200sq ft",
      bedRoom: 4,
      bathRoom: 4,
      beds: 4,
      games: 2, //for first page
    },
    Equipments: {
      outside: [
        "Private pool",
        "Private hot tub",
        "Sunloungers",
        "Covered terrace",
        "Outdoor lounge area",
      ],
      inside: [
        "Air-conditioned",
        "Smart TVs in living and bedrooms",
        "Game room",
        "Wifi",
        "Washer and dryer",
        "Iron and ironing board",
      ],
    },
  },
  {
    name: "Hartman",
    location: {
      country: "Caribbean",
      region: "Grenada",
      city: "Mount Hartman Bay",
    },
    startingPrice: "10000",
    images: [
      "product8/1.jpg",
      "product8/2.jpg",
      "product8/3.jpg",
      "product8/4.jpg",
      "product8/5.jpg",
      "product8/6.jpg",
      "product8/7.jpg",
      "product8/8.jpg",
      "product8/9.jpg",
      "product8/10.jpg",
      "product8/11.jpg",
      "product8/12.jpg",
      "product8/13.jpg",
      "product8/14.jpg",
      "product8/15.jpg",
      "product8/16.jpg",
      "product8/17.jpg",
      "product8/18.jpg",
      "product8/19.jpg",
      "product8/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "This luxury seven-acre gated estate offers enough space across three unbelievable properties to sleep up to 32 guests in unrivaled comfort, split with eight bedrooms in the Main House and four in each the Bay View Villa and Beach House. Offering phenomenal views, private infinity pools, a home gym, and private bar areas, this estate truly is the height of luxury. By booking the entire estate, ensure complete privacy when enjoying the estate amenities such as the private beach, outdoor movie screen and fire pit, and allow a team of staff to make your stay as comfortable as possible while you enjoy your Grenadian vacation. Additional guests can be accommodated for a fee of $100 per adult and $50 per child. To see how amenities are spread across each property, please refer to individual listings",
    Facilities: {
      capacity: 32,
      BuildArea: "4200sq ft",
      bedRoom: 4,
      bathRoom: 16,
      beds: 4,
      games: 4, //for first page
    },
    Equipments: {
      outside: [
        "2 private infinity pools",
        "Private pool",
        "2 hot tubs",
        "Swim-up bar",
        "Private balconies",
        "Roof terrace",
        "Sunloungers",
        "Pool decks",
        "Hammock",
        "Gazebo",
        "BBQ",
        "Outdoor tiki kitchen",
        "Alfresco dining area",
        "Outdoor lounge area",
        "Poolside lounge area",
        "Landscaped gardens",
      ],
      inside: [
        "Flat-screen TVs in all bedrooms and two living areas",
        "Home gym in Main House",
        "Grand piano in Main House",
        "Mini bar and tea/coffee in each bedroom",
        "Fully equipped kitchens",
        "2 private hot tubs",
      ],
    },
  },
  {
    name: "Anzio",
    location: {
      country: "Europe",
      region: "Italy",
      city: "MLazio",
    },
    startingPrice: "4000",
    images: [
      "product9/1.jpg",
      "product9/2.jpg",
      "product9/3.jpg",
      "product9/4.jpg",
      "product9/5.jpg",
      "product9/6.jpg",
      "product9/7.jpg",
      "product9/8.jpg",
      "product9/9.jpg",
      "product9/10.jpg",
      "product9/11.jpg",
      "product9/12.jpg",
      "product9/13.jpg",
      "product9/14.jpg",
      "product9/15.jpg",
      "product9/16.jpg",
      // "product9/17.jpg",
      // "product9/18.jpg",
      // "product9/19.jpg",
      // "product9/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "This amazing seven-bedroom, seven-bathroom home offers enough luxury living space to sleep fifteen guests comfortably, and is ideally located in Anzio, just a short walk from the sea, or a short drive or train ride from the Italian capital. Inside highlights include a spacious, open-plan living and dining area, a fully-equipped kitchen with a breakfast bar, and a private home gym with a range of equipment. Outside, you will find several terraces with plenty of space for alfresco dining and outdoor lounging. The property is surrounded by a lush, verdant garden, and an open terrace with a selection of sunloungers and a private swimming pool is perfect for enjoying a relaxing dip.",
    Facilities: {
      capacity: 15,
      BuildArea: "2100sq ft",
      bedRoom: 7,
      bathRoom: 6,
      beds: 6,
      games: 2, //for first page
    },
    Equipments: {
      outside: [
        "Private pool",
        "Veranda",
        "Sunloungers",
        "Alfresco dining area",
        "Outdoor lounge area",
        "Poolside lounge area",
        "Landscaped gardens",
      ],
      inside: [
        "Flat-screen TVs in all bedrooms and two living areas",
        "Home gym in Main House",
        "Grand piano in Main House",
        "Mini bar and tea/coffee in each bedroom",
        "Fully equipped kitchens",
        "2 private hot tubs",
      ],
    },
  },
  {
    name: "Limones",
    location: {
      country: "Europe",
      region: "Spain",
      city: "Costa Blanca",
    },
    startingPrice: "542",
    images: [
      "product10/1.jpg",
      "product10/2.jpg",
      "product10/3.jpg",
      "product10/4.jpg",
      "product10/5.jpg",
      "product10/6.jpg",
      "product10/7.jpg",
      "product10/8.jpg",
      "product10/9.jpg",
      "product10/10.jpg",
      "product10/11.jpg",
      "product10/12.jpg",
      "product10/13.jpg",
      "product10/14.jpg",
      "product10/15.jpg",
      "product10/16.jpg",
      // "product10/17.jpg",
      // "product10/18.jpg",
      // "product10/19.jpg",
      // "product10/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "This beautiful villa is located in the exclusive Cometa III urbanization set just above the bustling and lively resort of Calpe. This villa offers panoramic views from its elevated position. The property is set over two levels. Leading through the main entrance will lead you into the spacious lounge area with dining facilities, separate kitchen, three bedrooms and two bathrooms. An exterior stairway will lead you down to two separate apartments each with a lounge and kitchenette, a bedroom with a shower room.The villa has been furnished thoughtfully to a very high standard by its proud owner and comes complete with air-conditioning in the main lounge and all of the bedrooms. Downstairs, the air-conditioning units in the lounges will cool the whole open-planned apartments. WiFi is also available as well as UK TV channels and table tennis for the family. There is a Rattan table and chairs and comfortable seating for those relaxing evenings with the family. A large 12m Roman shaped swimming pool set in a mature garden with decking to the side, giving plenty of choice of where to sunbathe.",
    Facilities: {
      capacity: 10,
      BuildArea: "1900sq ft",
      bedRoom: 5,
      bathRoom: 4,
      beds: 5,
      games: 2, //for first page
    },
    Equipments: {
      outside: ["Veranda", "dining area", "Outdoor lounge area"],
      inside: [
        "Flat-screen TVs in all bedrooms and two living areas",
        "Home gym in Main House",
        "Fully equipped kitchens",
      ],
    },
  },
  {
    name: "GoldenXest",
    location: {
      country: "Europe",
      region: "Greece",
      city: "Crete",
    },
    startingPrice: "1200",
    images: [
      "product11/1.jpg",
      "product11/2.jpg",
      "product11/3.jpg",
      "product11/4.jpg",
      "product11/5.jpg",
      "product11/6.jpg",
      "product11/7.jpg",
      "product11/8.jpg",
      "product11/9.jpg",
      "product11/10.jpg",
      "product11/11.jpg",
      "product11/12.jpg",
      "product11/13.jpg",
      "product11/14.jpg",
      "product11/15.jpg",
      "product11/16.jpg",
      // "product11/17.jpg",
      // "product11/18.jpg",
      // "product11/19.jpg",
      // "product11/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "A spectacular holiday home with a private pool and 3 bedrooms, finished to the highest standard, and ideally located just a few steps away from the port of the famous resort of Hersonisos. With shops, restaurants and bars within walking distance, a car is not required! This beautiful villa combines modern with tradition, in a unique mix, in order to offer a truly exceptional holiday experience even to the most demanding guests.Inside, the villa has been carefully designed with attention to the details in mind. Antique pieces, modern comforts, stylish details. The kitchen is fully equipped, the lounge is comfortable, the 3 bedrooms airy and welcoming. There are 2 double bedrooms and 1 twin bedroom, together with 2 family bathrooms (one of which is equipped with a bathtub) and one WC. For the comfort of our guests, the villa is air conditioned.",
    Facilities: {
      capacity: 6,
      BuildArea: "1600sq ft",
      bedRoom: 4,
      bathRoom: 3,
      beds: 4,
      games: 1, //for first page
    },
    Equipments: {
      outside: ["Veranda", "dining area", "Outdoor lounge area", "Pool Area"],
      inside: [
        "Flat-screen TVs in all bedrooms and living areas",
        "Home gym in Main House",
        "Fully equipped kitchens",
      ],
    },
  },
  {
    name: "Vega",
    location: {
      country: "Europe",
      region: "Portugal",
      city: "Algarve",
    },
    startingPrice: "1800",
    images: [
      "product12/1.jpg",
      "product12/2.jpg",
      "product12/3.jpg",
      "product12/4.jpg",
      "product12/5.jpg",
      "product12/6.jpg",
      "product12/7.jpg",
      "product12/8.jpg",
      "product12/9.jpg",
      "product12/10.jpg",
      "product12/11.jpg",
      "product12/12.jpg",
      "product12/13.jpg",
      "product12/14.jpg",
      "product12/15.jpg",
      "product12/16.jpg",
      // "product11/17.jpg",
      // "product11/18.jpg",
      // "product11/19.jpg",
      // "product11/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "This villa is an elegant four-bedroom hideaway in the seaside resort of Gale. It is superbly positioned in a tranquil area, with the old town of Albufeira close by. The villa opens out onto a spacious, manicured lawn and gorgeous swimming pool. Sun loungers and a poolside table and chairs offer total relaxation under the clear blue skies of The Algarve.Lots of floor to ceiling windows and light decor offer a breezy feel to the villa. Immaculately presented, with sunny highlights throughout, it has a relaxing vibe. At night the villa takes on a whole, new vibe, with a dramatically lit turquoise pool and soft, well-appointed lightingaround the villa. Great to relax with a drink and enjoy the stars.There are a good selection of local Portuguese restaurants and shops within a short stroll of the villa. Famed for its dramatic rock formations and golden sand, Praia Gale is one of the closest beaches. Nestled against the rocky coves, this pale sand beach has lots of rock pools for the kids to explore and really fun, splashy waves.",
    Facilities: {
      capacity: 10,
      BuildArea: "1400sq ft",
      bedRoom: 5,
      bathRoom: 4,
      beds: 4,
      games: 1, //for first page
    },
    Equipments: {
      outside: [
        "Private pool",
        "Sunloungers",
        "Covered terrace with table and chairs",
        "Brick built BBQ",
        "Manicured lawn",
        "Table tennis",
      ],
      inside: [
        "Flat-screen TVs in all bedrooms and living areas",
        "Home gym in Main House",
        "Fully equipped kitchens",
        "wifi",
        "Air Conditioner",
      ],
    },
  },
  {
    name: "Bang Por",
    location: {
      country: "Asia",
      region: "Thailand",
      city: "Koh Samui",
    },
    startingPrice: "2100",
    images: [
      "product13/1.jpg",
      "product13/2.jpg",
      "product13/3.jpg",
      "product13/4.jpg",
      "product13/5.jpg",
      "product13/6.jpg",
      "product13/7.jpg",
      "product13/8.jpg",
      "product13/9.jpg",
      "product13/10.jpg",
      "product13/11.jpg",
      "product13/12.jpg",
      "product13/13.jpg",
      "product13/14.jpg",
      "product13/15.jpg",
      "product13/16.jpg",
      // "product11/17.jpg",
      // "product11/18.jpg",
      // "product11/19.jpg",
      // "product11/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "This villa is an elegant four-bedroom hideaway in the seaside resort of Gale. It is superbly positioned in a tranquil area, with the old town of Albufeira close by. The villa opens out onto a spacious, manicured lawn and gorgeous swimming pool. Sun loungers and a poolside table and chairs offer total relaxation under the clear blue skies of The Algarve.Lots of floor to ceiling windows and light decor offer a breezy feel to the villa. Immaculately presented, with sunny highlights throughout, it has a relaxing vibe. At night the villa takes on a whole, new vibe, with a dramatically lit turquoise pool and soft, well-appointed lightingaround the villa. Great to relax with a drink and enjoy the stars",
    Facilities: {
      capacity: 10,
      BuildArea: "1400sq ft",
      bedRoom: 5,
      bathRoom: 5,
      beds: 5,
      games: 1, //for first page
    },
    Equipments: {
      outside: [
        "Large kidney shaped infinity-edge pool",
        "Expansive multi-level sun terrace",
        "Sunken jacuzzi",
        "Luxury loungers and daybeds",
        "Alfresco dining area with BBQ facilities",
        "Exquisite ocean views",
        "Lush tropical gardens",
      ],
      inside: [
        "Flat-screen TVs in all bedrooms and living areas",
        "Home gym in Main House",
        "Fully equipped kitchens",
        "wifi",
        "Air Conditioner",
      ],
    },
  },
  {
    name: "Choeng ",
    location: {
      country: "Asia",
      region: "Thailand",
      city: "Koh Samui",
    },
    startingPrice: "3800",
    images: [
      "product14/1.jpg",
      "product14/2.jpg",
      "product14/3.jpg",
      "product14/4.jpg",
      "product14/5.jpg",
      "product14/6.jpg",
      "product14/7.jpg",
      "product14/8.jpg",
      "product14/9.jpg",
      "product14/10.jpg",
      "product14/11.jpg",
      "product14/12.jpg",
      "product14/13.jpg",
      "product14/14.jpg",
      "product14/15.jpg",
      "product14/16.jpg",
      // "product11/17.jpg",
      // "product11/18.jpg",
      // "product11/19.jpg",
      // "product11/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "This villa is an elegant four-bedroom hideaway in the seaside resort of Gale. It is superbly positioned in a tranquil area, with the old town of Albufeira close by. The villa opens out onto a spacious, manicured lawn and gorgeous swimming pool. Sun loungers and a poolside table and chairs offer total relaxation under the clear blue skies of The Algarve.Lots of floor to ceiling windows and light decor offer a breezy feel to the villa. Immaculately presented, with sunny highlights throughout, it has a relaxing vibe. At night the villa takes on a whole, new vibe, with a dramatically lit turquoise pool and soft, well-appointed lightingaround the villa. Great to relax with a drink and enjoy the stars.There are a good selection of local Portuguese restaurants and shops within a short stroll of the villa. Famed for its dramatic rock formations and golden sand, Praia Gale is one of the closest beaches. Nestled against the rocky coves, this pale sand beach has lots of rock pools for the kids to explore and really fun, splashy waves.",
    Facilities: {
      capacity: 18,
      BuildArea: "3000sq ft",
      bedRoom: 8,
      bathRoom: 8,
      beds: 14,
      games: 4, //for first page
    },
    Equipments: {
      outside: [
        "Huge infinity-edge pool",
        "Shallow pool area with sunken loungers",
        "Expansive multi-level sun terrace",
        "Luxury loungers, sofas and daybeds",
        "Poolside massage sala",
        "Bar area with BBQ, pool table and LCD/TV",
        "Exquisite ocean views",
        "Landscaped gardens",
        "Ornate wood carvings and features",
      ],
      inside: [
        "Multi level living area with panormaic ocean views",
        "Fully fitted modern kitchen with breakfast bar",
        "Seaview lounge with foldaway glass doors",
        "Stylish sea view dining area with seating for 12",
        "Numerous alcoves, balconies and chill out zones",
        "TV lounge with sofas, coffee table, TV/DVD",
        "Alfresco dining areas",
        "Separate 'teen pad' living area",
      ],
    },
  },
  {
    name: "Lulito",
    location: {
      country: "Asia",
      region: "Indonesia",
      city: "Bali",
    },
    startingPrice: "6100",
    images: [
      "product16/1.jpg",
      "product16/2.jpg",
      "product16/3.jpg",
      "product16/4.jpg",
      "product16/5.jpg",
      "product16/6.jpg",
      "product16/7.jpg",
      "product16/8.jpg",
      "product16/9.jpg",
      "product16/10.jpg",
      "product16/11.jpg",
      "product16/12.jpg",
      "product16/13.jpg",
      "product16/14.jpg",
      "product16/15.jpg",
      "product16/16.jpg",
      // "product11/17.jpg",
      // "product11/18.jpg",
      // "product11/19.jpg",
      // "product11/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "In the heart of Seminyaks upmarket Oberoi district, close to the beach and Balis top restaurants, this four-bedroom private holiday rental villa with its evocative, white-on-white colonial architecture exudes elegance and plantation-style charm.Framed by four living and sleeping pavilions, a generous pool forms the inviting centrepiece at Villa Lulito. Bamboo and wicker - steamer chairs, casually draped mosquito nets, brass ceiling fans and white walls ornamented with vintage posters, hark back to an era of exotic travel. And on hand to guarantee a luxury holiday experience is a capable crew of staff, including a private chef, butlers, housekeepers and a villa manager.Villa Lulito has an enviable position at the centre ofthe upmarket Oberoi area of Seminyak, and is just a five-minute walk from Petitenget Beach and the much-lauded Ku De Ta restaurant and beach club. Heading out of the villa by foot in either direction will take you past five star hotels and other luxury villas, cafes, restaurants, shops and spas. A short taxi ride along the same street opens up a wider world of gourmet delights with some of Balis, and indeed Asias, best restaurants, bars and beach clubs close by.",
    Facilities: {
      capacity: 12,
      BuildArea: "3200sq ft",
      bedRoom: 6,
      bathRoom: 8,
      beds: 10,
      games: 3, //for first page
    },
    Equipments: {
      outside: [
        "Landscaped tropical gardens",
        "15-metre pool, beautifully lit at night",
        "Large stone terraces furnished",
        "sun loungers and cushioned club chairs",
        "Covered terrace",
        "comfortable chairs and tables at pool",
      ],
      inside: [
        "Spacious, open-fronted elegant dining room",
        "Fan cooled living area ",
        "large comfortable couches ",
        "cushioned club chairs",
        "flat screen TV, DVD player, books",
        "Bose sound system with iPod dock",
        "loaded iPod and library.",
        "Charming garden pavilion ",
      ],
    },
  },
  {
    name: "LeGa",
    location: {
      country: "Asia",
      region: "Indonesia",
      city: "Bali",
    },
    startingPrice: "4100",
    images: [
      "product15/1.jpg",
      "product15/2.jpg",
      "product15/3.jpg",
      "product15/4.jpg",
      "product15/5.jpg",
      "product15/6.jpg",
      "product15/7.jpg",
      "product15/8.jpg",
      "product15/9.jpg",
      "product15/10.jpg",
      "product15/11.jpg",
      "product15/12.jpg",
      "product15/13.jpg",
      "product15/14.jpg",
      "product15/15.jpg",
      "product15/16.jpg",
      // "product11/17.jpg",
      // "product11/18.jpg",
      // "product11/19.jpg",
      // "product11/20.jpg",
    ],
    availableDates: {
      startDate: "",
      endDate: "",
    },
    Description:
      "5 bedroom beachfront villa with private pool at SeminyakSet in one of Balis most coveted positions, right on Batubelig Beach, and just to the north of Seminyak, Villa LeGa is a fully staffed, luxury private villa with five spacious ensuite bedrooms, a 12-metre swimming pool, immaculate gardens, butlers and private chef, stunning 180-degree sunset views, and an open-plan living and dining room as well as an upper storey TV lounge. Two rooftop decks are ideally positioned to soak up the sunset and ocean views. With so many facilities and its unique beachfront but close-to-town location, Villa LeGa is ideal for families or groups of friends looking for something extra special.",
    Facilities: {
      capacity: 10,
      BuildArea: "2100sq ft",
      bedRoom: 5,
      bathRoom: 5,
      beds: 5,
      games: 4, //for first page
    },
    Equipments: {
      outside: [
        "Immaculate walled garden with 12-metre pool ",
        "sun deck and loungers",
        "Upper-floor 'sunset' terrace furnished",
        "Intimate rooftop deck with sun loungers and umbrella",
      ],
      inside: [
        "Elegant dining area seating up to 12 guests",
        "Comfortable open-sided living room ",
        "large satellite-channel TV and DVD player",
        "Air-conditioned TV lounge on first floor",
        "SPA",
        "Wifi",
      ],
    },
  },
];

module.exports = villas;
